# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteamAutoshutdown < Formula
  desc "Automatically shuts down your computer when Steam downloads finish."
  homepage "https://github.com/k0wl0n/steam-autoshutdown"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.2/steam-autoshutdown_Darwin_x86_64.tar.gz"
      sha256 "6a7919c4aa80f5c8fe7f9b5d0fd432e707a68116c019a58103da07f8765f7e12"

      def install
        bin.install "steam-autoshutdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.2/steam-autoshutdown_Darwin_arm64.tar.gz"
      sha256 "c5e60439078c5d160932f450711ad6715304bcd0108a9352a18924c2eead2fbe"

      def install
        bin.install "steam-autoshutdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.2/steam-autoshutdown_Linux_x86_64.tar.gz"
      sha256 "34c35c649804a5a45486c29264ca8360457a1bf93c679138fa337474ba1a64a9"
      def install
        bin.install "steam-autoshutdown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.2/steam-autoshutdown_Linux_arm64.tar.gz"
      sha256 "8d53afd5b4b54bc0b5e00df73e99e64da64eb865b34d4edca53bcd6def03f8b1"
      def install
        bin.install "steam-autoshutdown"
      end
    end
  end

  test do
    system "#{bin}/steam-autoshutdown --version"
  end
end
