# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gctx < Formula
  desc "GCloud Multi-Account Manager (Go + Cobra)"
  homepage "https://github.com/k0wl0n/gctx"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.5.1/gctx-0.5.1-darwin-amd64.tar.gz"
      sha256 "79688413859e94764ee1e7efadbdd77ff343ac27facafb2fe532d144c03df905"

      define_method(:install) do
        bin.install "gctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.5.1/gctx-0.5.1-darwin-arm64.tar.gz"
      sha256 "4a07c2f6e00bd672eb43c5d5a6cbd3a80c32eeccfa19c3ffd7cac1ca4fcf2d76"

      define_method(:install) do
        bin.install "gctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.5.1/gctx-0.5.1-linux-amd64.tar.gz"
      sha256 "0c9d70d9b1f6d6c90f9f44a68f847dba8dee96aeba60606c172f58af0406ea37"
      define_method(:install) do
        bin.install "gctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.5.1/gctx-0.5.1-linux-arm64.tar.gz"
      sha256 "97ace4ca9eac1f9570ff6a0c58bc6e57a87f7488e2dc70c1ee898ffb4f2bf059"
      define_method(:install) do
        bin.install "gctx"
      end
    end
  end
end
