# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gctx < Formula
  desc "GCloud Multi-Account Manager (Go + Cobra)"
  homepage "https://github.com/k0wl0n/gctx"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.2.5/gctx-0.2.5-darwin-amd64.tar.gz"
      sha256 "8bc16e01a9b7b749a9fbc0b4db5ef4bd7817e8c0faeb20543d2eaf695e6d9be3"

      def install
        bin.install "gctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.2.5/gctx-0.2.5-darwin-arm64.tar.gz"
      sha256 "ca3890209025ad27491cc3277d5c8d9fe16dd0947a0c18c010741261e0608abd"

      def install
        bin.install "gctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.2.5/gctx-0.2.5-linux-amd64.tar.gz"
      sha256 "b3ef1062d9131219e5cd7f2ca59e9bade88327a24d5474d88e8808bcdcaa420b"
      def install
        bin.install "gctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/gctx/releases/download/v0.2.5/gctx-0.2.5-linux-arm64.tar.gz"
      sha256 "9bc71b0b48bf9333616fa3a9cb2845e1b67e03eabed4a142cb99e46777d22913"
      def install
        bin.install "gctx"
      end
    end
  end
end
