# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteamAutoshutdown < Formula
  desc "Automatically shuts down your computer when Steam downloads finish."
  homepage "https://github.com/k0wl0n/steam-autoshutdown"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.3/steam-autoshutdown_Darwin_x86_64.tar.gz"
      sha256 "06b6b7533bd5abb522098b56326498f6aa1fa8dafc38883086995205c47c0215"

      def install
        bin.install "steam-autoshutdown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.3/steam-autoshutdown_Darwin_arm64.tar.gz"
      sha256 "de32db6f6578dae34aa42af9486a3677adb1d0250b4164f189d881c5253598af"

      def install
        bin.install "steam-autoshutdown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.3/steam-autoshutdown_Linux_x86_64.tar.gz"
      sha256 "6f679bd1d3685a8a925d046cda1420d0cbfce3a35e3019758479004aca974af0"
      def install
        bin.install "steam-autoshutdown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k0wl0n/steam-autoshutdown/releases/download/v0.1.3/steam-autoshutdown_Linux_arm64.tar.gz"
      sha256 "a5a89352951aa356a1f105561ab4719ff23551acd34fbeef06d22ab4ef186a16"
      def install
        bin.install "steam-autoshutdown"
      end
    end
  end

  test do
    system "#{bin}/steam-autoshutdown --version"
  end
end
